csv_parce_product:
    resource: "@CSVParceBundle/Resources/config/routing/product.yml"
    prefix:   /product

csv_parce_homepage:
    path:     /
    defaults: { _controller: CSVParceBundle:Default:index }
